### ISSUE TITLE
[BUG] 1.16.1 abnormal player scores

### ISSUE THREAD

**Issue by donvdp** [IridiumLLC/IridiumSkyblock#215]
Hi there, for some reason users on my skyblock server keep getting a weird abnormal score... i have tried to reproduce this, but i dont know how this is happening.  see [this](https://imgur.com/5CRAWFa) image.

**To Reproduce**
I dont know, i have tried to reproduce, but i cant figure out how this would happen.
I have made a new island for myself and put the same ammount of blocks on that island as one of the corrupt player islands... but my island score is calculated properly.
see [this](https://imgur.com/5CRAWFa) image. in this image i put an excel calulation togetjher with screen of the blockvalue file and the actual ingame score.

I have chatted with SlashRemix and he made me execute a bunch of commands... but this does not fix it.
i tried:
- /is update all
- /is reload

SlashRemix warned me that "/is update all" would cause some lagg... but it didnt cause any lag on my server. perhaps some function is not being called properly?

Im running 
- 1.16.1.  papermc build 133
- [this](https://imgur.com/7slIQRy) is my plugins list

here are all my iridiumskyblock plugin files.
[https://we.tl/t-JvL81rfseO](https://we.tl/t-JvL81rfseO)

**Comment by donvdp** [comment]
UPDATE:::
I appear to be able to reproduce this issue... the plugin called "EpicSpawners" is messing up the island score.
Though i am quite fond of the plugin and on your website you say to be supporting this plugin. Can you fix ?

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there

**Comment by donvdp** [comment]
i have tried that beta-version.

Unfortinatly this did not resolve the issue, island scores still go out of whack when spanwers are placed.....

**Comment by donvdp** [comment]
We switched to fabledskyblock due to lack of support of iridiumskyblock. The irridium skyblock plugin contains too many bugs to propperly be used.
