### ISSUE TITLE
Exceptions when doing /is warps[BUG]

### ISSUE THREAD

**Issue by TheRealRude** [IridiumLLC/IridiumSkyblock#558]
[23:22:30 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.6.7 generated an exception while executing task 252734
java.lang.NullPointerException: null
        at com.iridium.iridiumskyblock.gui.WarpGUI.addContent(WarpGUI.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-457]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-457]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

Spams when trying to open /is warps menu

**Comment by dlsf** [comment]
That looks very weird... What version of Java are you using?

**Comment by dlsf** [comment]
This looks weird, this issue should have been fixed by [this commit](https://github.com/IridiumLLC/IridiumSkyblock/commit/a380ea7b1578fd1b4a62ebcb1380d903a01eb37a). It is kinda hard to see what version of the code you are running, as the code that is causing the error often changed in the past weeks, so I can't really tell what the issue is right now. Any ideas @PeachesMLG?

**Comment by TheRealRude** [comment]
1.16.5 Newest version of plugin

**Comment by TheRealRude** [comment]
Apparently not only on /is warps. It happens randomly.

**Comment by PeachesMLG** [comment]
Ye this is already fixed

**Comment by dlsf** [comment]
But the stack trace is from 2.6.7, so it's apparently still an issue @PeachesMLG

**Comment by PeachesMLG** [comment]
sorry  should have clarified, I fixed it in 3.0.0
